sudo: required

services:
  - docker

script:
  - docker build -t kin-client .
  - docker run --name kin -d -e API_HOSTNAME=kin.example.com kin-client
  - echo "Container has been started... waiting a few seconds for initialization!"
  - sleep 60
  - docker exec kin bash -c "apt-get update && apt-get install curl -y --no-install-recommends && curl -f localhost:8080"
